name: auth_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/home1.png"
    - "assets/images/home2.png"
    - "assets/images/Build.png"
    - "assets/images/home2.png"
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf

    - family: Akaya Telivigala
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf
